<?php
/**
 * @version 7.4
 */
if ($this->pageCount) { ?>
    <div class="text-center">
        <ul class="pagination">
            <!-- Previous page link -->
            <?php if ($this->previous) { ?>
                <li>
                    <a href="<?php echo $this->url(array('page' => $this->previous), null, true); ?>">
                        &lt; <?php echo $this->_('Previous'); ?>
                    </a>
                </li>
            <?php } ?>

            <?php if (min($this->pagesInRange) > 1) { ?>
                <li>
                    <a href="<?php echo $this->url(array('page' => 1), null, true); ?>">1</a>
                </li>
            <?php } ?>

            <?php if (min($this->pagesInRange) > 2) { ?>
                <li class="disabled">
                    <a href="#">...</a>
                </li>
            <?php } ?>
            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page) { ?>
                <li <?php echo ($page == $this->current) ? 'class="active"' : ''; ?>>
                    <a href="<?php echo $this->url(array('page' => $page), null, true); ?>"><?php echo $page; ?></a>
                </li>
            <?php } ?>

            <?php if (max($this->pagesInRange) < ($this->last - 1)) { ?>
                <li class="disabled">
                    <a href="#">...</a>
                </li>
            <?php } ?>
            <?php if (max($this->pagesInRange) < $this->last) { ?>
                <li>
                    <a href="<?php echo $this->url(array('page' => $this->last), null, true); ?>"><?php echo $this->last; ?></a>
                </li>
            <?php } ?>
            <!-- Next page link -->
            <?php if ($this->next) { ?>
                <li>
                    <a href="<?php echo $this->url(array('page' => $this->next), null, true); ?>"><?php echo $this->_('Next'); ?>
                        &gt;</a>
                </li>
            <?php } ?>
        </ul>

    </div>
<?php } ?>