
<ul class="nav nav-tabs nav-members hidden-xs">
    <?php foreach ($this->menu->pages as $page) { ?>
        <?php if ((!$page->settings || (intval($this->settings[(string) $page->settings['name']]) == $page->settings['value'])) &&
               $this->navigation()->accept($page)) { ?>
            <li <?php echo ($page->isActive(true)) ? 'class="active"' : ''; ?>>
                <a href="<?php echo $this->url($page->params); ?>">
                    <?php echo $page->label; ?>
                </a>
            </li>
        <?php } ?>
    <?php } ?>
</ul>

