<?php
/**
 * @version 7.6
 */

$label = $element->getLabel();
$description = $element->getDescription();
$subtitle = $element->getSubtitle();

if (!$element->isHidden()) { ?>
    <?php if (!empty($subtitle)) { ?>
        <h4 class="headline">
            <i class="fa fa-angle-right"></i>
            <span><?php echo $subtitle; ?></span>
        </h4>
    <?php } ?>

    <div class="form-group">
        <label class="col-sm-3 control-label">
            <?php if (!empty($label)) { ?>
                <?php echo $label; ?>
            <?php } ?>
        </label>

        <div class="col-sm-9">
            <?php echo $element->render(); ?>

            <?php if (!empty($description)) { ?>
                <span class="help-block">
                    <?php echo $description; ?>
                </span>
            <?php } ?>
        </div>
    </div>
<?php } ?>