<h4>
    <?php echo $this->_('Account Balance Exceeded Notification'); ?>
</h4>
<p>
    <?php echo sprintf(
        $this->_('The account balance for your user <strong>%s</strong> is %s and has exceeded the maximum debit limit of %s.'),
        $this->data['user']['username'],
        $this->amount($this->data['user']['balance']),
        $this->amount($this->data['user']['max_debit'])); ?>
</p>
<?php if ($this->settings['suspend_over_limit_accounts'] || $this->data['user']['active'] == 0) { ?>
    <p>
        <?php echo $this->_('Your account has been suspended.'); ?>
    </p>
<?php
}
else if ($this->settings['suspension_days']) {
    ?>
    <p>
        <?php echo sprintf(
            $this->_('Your account will be automatically suspended in %s days.'),
            $this->settings['suspension_days']); ?>
    </p>
<?php } ?>

<p>
    <?php echo $this->_('Please'); ?>
    [ <a
        href="<?php echo $this->sitePath . $this->url(array('module' => 'app', 'controller' => 'payment', 'action' => 'credit-balance'), null, false, null, false); ?>">
        <?php echo $this->_('click here'); ?>
    </a> ]
    <?php echo $this->_('to clear your account balance.'); ?> <br>
    <?php echo $this->_('Please note that you will have to login first.'); ?>
</p>
<p>
    <?php echo $this->_('Best regards'); ?> <br>
    <?php echo $this->siteName; ?></p>
</p>
