<?php
/**
 * @version 7.4
 */

echo $this->data['content'];
?>

<p style="text-align: center; border-top: 1px solid #e0e0e0; margin-top: 20px; padding-top: 10px;">
    <small>
        <?php echo $this->_('To no longer receive our newsletter'); ?>
        <a href="<?php echo $this->sitePath . $this->url($this->data['unsubscribe_link'], null, false, null, false, false); ?>">
            <?php echo $this->_('click here'); ?>.
        </a>
    </small>
</p>