<table class="table table-striped">
    <thead>
        <tr>
            <th>Item Details</th>
            <th class="size-mini">Status</th>
            <th class="size-mini">Options</th>
        </tr>

    </thead>
    <tbody>
        <tr>
            <td>Test</td>
            <td><span class="label label-info">Unpaid</span></td>
            <td>Delete</td>
        </tr>
        <tr>
            <td>Test 2</td>
            <td><span class="label">Unpaid</span></td>
            <td>Delete</td>
        </tr>
        <tr>
            <td>Test 3</td>
            <td><span class="label">Unpaid</span></td>
            <td>Delete</td>
        </tr>

    </tbody>
</table>