<?php
/**
 * @version 7.3
 */

/** @var \Ppb\Db\Table\Row\User $user */
if ($user->canPaySignupFee()) { ?>
    <blockquote class="bq bq-alert">
        <?php echo $this->_('User signup fee not paid.'); ?>
    </blockquote>
    <?php echo $this->action('user-signup', 'payment', 'app', array('id' => $user['id'])); ?>
<?php
}
else {
    ?>
    <?php if ($this->settings['signup_settings'] == 1) { ?>
        <p class="lead">
            <?php echo $this->_('Your email address is not verified.'); ?>
        </p>

        <p>
            <?php echo $this->_('Please click on the email verification link from the registration confirmation email that '
                . 'you have received when you have registered with our site in order to activate your account.'); ?>
        </p>
    <?php
    }
    else if ($this->settings['signup_settings'] == 2) {
        ?>
        <p class="lead">
            <?php echo $this->_('Your account is pending approval.'); ?>
        </p>
        <p>
            <?php echo $this->_("Your account hasn't been approved by the administrator yet or you haven't verified your email address. "
                . "If the account is pending approval, you will be notified by email when the account will be activated. "
                . "Otherwise you can request the verification email to be sent again."); ?>
        </p>
    <?php } ?>
    <form action="<?php echo $this->url(array('module' => 'members', 'controller' => 'user', 'action' => 'activate')); ?>" method="post">
        <?php echo $this->formElement('submit', 'resend_email', $this->_('Resend Email'))
            ->setAttributes(array('class' => 'btn'))
            ->render();
        ?>
    </form>
<?php } ?>


