<?php
/**
 * @version 7.2
 */
?>
<div class="row login-box">
    <div class="col-sm-4 col-sm-offset-2 first">
        <div class="content">
            <h3 class="headline">
                <span><?php echo $this->_('New Users'); ?></span>
            </h3>

            <div><?php echo $this->_("Don't have an account? To register, please click on the link below."); ?></div>
        </div>
        <div>
            <a href="<?php echo $this->url(null, 'members-register'); ?>"
               class="btn btn-default">
                <?php echo $this->_('Create an Account'); ?></a>
        </div>
    </div>
    <div class="col-sm-4">
        <?php echo $this->form; ?>
    </div>
</div>


