<?php
/**
 * @version 7.5
 */
?>
<form class="form-modal" action="<?php echo $this->url(null, 'members-register'); ?>" method="post">
    <p class="text-center">
        <small>
            <?php echo $this->_('Already have an account ?'); ?>
            <a href="<?php echo $this->url(null, 'members-login'); ?>"><?php echo $this->_('Log in'); ?></a>
        </small>
    </p>
    <?php echo $this->formElement('csrf', 'csrf'); ?>
    <input type="text" placeholder="<?php echo $this->_('Username'); ?>" name="username" class="form-control" value="">
    <input type="text" placeholder="<?php echo $this->_('Email'); ?>" name="email" class="form-control" value="">
    <input type="password" placeholder="<?php echo $this->_('Password'); ?>" name="password" class="form-control"
           value="">
    <input type="password" placeholder="<?php echo $this->_('Confirm Password'); ?>" name="password_confirm"
           class="form-control">

    <?php if ($this->settings['enable_recaptcha'] && $this->settings['recaptcha_registration']) { ?>
        <?php echo $this->formElement('\\Ppb\\Form\\Element\\ReCaptcha', 'recaptcha')->render(); ?>
    <?php } ?>
    <label class="checkbox">
        <input name="newsletter_subscription" type="checkbox" class="newsletter" value="1">
        <?php echo $this->_('Subscribe To Newsletter'); ?>
    </label>
    <?php if ($this->settings['enable_registration_terms']) { ?>
        <label class="checkbox">
            <input name="agree_terms" type="checkbox" class="terms" value="1">
            <?php echo $this->_('I have read and agree to the'); ?>
            <a href="<?php echo $this->url($this->settings['registration_terms_link']); ?>" target="_blank">
                <?php echo $this->_('Terms and Conditions'); ?></a>
            <?php echo $this->_('and'); ?>
            <a href="<?php echo $this->url($this->settings['registration_privacy_link']); ?>" target="_blank">
                <?php echo $this->_('Privacy Policy'); ?></a>
        </label>
    <?php } ?>
    <input class="btn btn-primary btn-lg btn-block" type="submit" name="submit"
           value="<?php echo $this->_('Sign Up'); ?>">

    <hr>
    <!--
    <p class="text-center">
        <small>or use your Facebook account</small>
    </p>
    <a href="#" class="btn btn-lg btn-default btn-block btn-register-facebook">
        <i class="fa fa-facebook-square"></i>
        Sign In Using Facebook
    </a>
    -->

</form>

