<h4>
    <?php echo $this->_('Password Reset'); ?>
</h4>

<p>
    <?php echo sprintf(
        $this->_('The password for your account on %s has been reset.'),
        $this->siteName); ?>
</p>

<div>
    <?php echo $this->_('Your updated account details are:'); ?>
</div>
<ul>
    <li>
        <?php echo $this->_('Username:'); ?>
        <b><?php echo $this->data['user']['username']; ?></b>
    </li>
    <li>
        <?php echo $this->_('Password:'); ?>
        <b><?php echo $this->data['password']; ?></b>
    </li>
</ul>
<p>
    <?php echo $this->_('Please'); ?>
    [ <a href="<?php echo $this->sitePath . $this->url(null, 'members-login', false, null, false); ?>">
        <?php echo $this->_('click here'); ?>
    </a> ]
    <?php echo $this->_('to log in.'); ?>
</p>
<p>
    <?php echo $this->_('Best regards'); ?> <br>
    <?php echo $this->siteName; ?>
</p>
