<h4>
    <?php echo $this->_('Thank you for registering.'); ?>
</h4>
<p>
    <?php echo $this->_('Your account has been created successfully.'); ?>
</p>

<div><?php echo $this->_('User Details:'); ?></div>
<ul>
    <li>
        <?php echo $this->_('Username:'); ?>
        <b><?php echo $this->data['username']; ?></b>
    </li>
    <li>
        <?php echo $this->_('Email:'); ?>
        <b><?php echo $this->data['email']; ?></b>
    </li>
</ul>
<p>
    <?php echo $this->_('Please'); ?>
    [ <a
        href="<?php echo $this->sitePath . $this->url(array('key' => $this->data['registration_key']), 'members-register-confirm', false, null, false); ?>">
        <?php echo $this->_('click here'); ?>
    </a> ]
    <?php echo $this->_('to confirm your email address.'); ?>
</p>
<p>
    <?php echo $this->_('Your account will be manually activated after being reviewed by an administrator.<br>'
        . 'You will be notified by email once your account will become active.'); ?>
</p>
<p>
    <?php echo $this->_('Best regards'); ?> <br>
    <?php echo $this->siteName; ?>
</p>
