<h4>
    <?php echo $this->_('Thank you for registering.'); ?></h4>
<p>
    <?php echo $this->_('Your account has been activated successfully.'); ?></p>

<div><?php echo $this->_('Your login details are:'); ?></div>
<ul>
    <li>
        <?php echo $this->_('Username:'); ?>
        <b><?php echo $this->data['username']; ?></b>
    </li>
    <li>
        <?php echo $this->_('Password: - hidden -'); ?>
    </li>
</ul>
<p>
    <?php echo $this->_('Please'); ?>
    [ <a href="<?php echo $this->sitePath . $this->url(null, 'members-login', false, null, false); ?>">
        <?php echo $this->_('click here'); ?>
    </a> ]
    <?php echo $this->_('to log in.'); ?>
</p>
<p>
    <?php echo $this->_('Best regards'); ?> <br>
    <?php echo $this->siteName; ?>
</p>
