<?php
/**
 * @version 7.4
 */
?>
<p>
    <?php echo sprintf(
        $this->_('One or more of your items you have listed on %s have been sold.'),
        $this->siteName); ?>
</p>

<?php echo $this->partial('partials/sale.phtml', array(
    'sale'        => $this->data['sale'],
    'postageDesc' => true,
    'caption'     => true,
    'type'        => 'sold')); ?>

<p>
    <?php echo $this->_('Best regards'); ?> <br>
    <?php echo $this->siteName; ?>
</p>

