<?php
/**
 * @version 7.6
 */
/** @var bool $connected */
/** @var bool $submitted */
/** @var string $httpHost */
/** @var string $documentRoot */

if ($connected) {
    if ($submitted) { ?>
    <blockquote>
        <?php echo sprintf(
            $this->_('Please <a href="%s">click here</a> to access your website. <br>'
                . '<strong>Important</strong>: If the activation key is invalid, you will be redirected back to this page.'),
            $this->url(null, 'app-home')); ?>
    </blockquote>
<?php
}
else {
    ?>
    <blockquote>
        <?php echo sprintf(
            $this->_('To generate your license activation key, please <a href="%s" target="_blank">click here</a> and use the data below:'),
            'http://www.phpprobid.com/activate-license');
        ?>
    </blockquote>

    <dl class="dl-horizontal">
        <dt><?php echo $this->_('HTTP Host'); ?></dt>
        <dd><?php echo $httpHost; ?></dd>
        <dt><?php echo $this->_('Document Root'); ?></dt>
        <dd><?php echo $documentRoot; ?></dd>
    </dl>
<?php } ?>

<?php echo $this->form; ?>
<?php } ?>