<?php if ($connected) { ?>
<?php if ($submitted) { ?>
    <blockquote>
        <?php echo sprintf(
            $this->_('Please <a href="%s">click here</a> to access your website.'),
            $this->url(null, 'app-home')); ?>
    </blockquote>
<?php
}
else {
    ?>
    <blockquote>
        <div><?php echo $this->_('You can import data from your PHP Pro Bid v6.x installation using this form.'); ?></div>
    </blockquote>
<?php } ?>

<?php echo $this->form; ?>
<?php } ?>