<?php if ($connected) { ?>
<?php if ($submitted) { ?>
    <blockquote>
        <?php echo sprintf(
            $this->_('Please <a href="%s">click here</a> to access your website.'),
            $this->url(null, 'app-home')); ?>
    </blockquote>
<?php
}
else {
    ?>
    <blockquote>
        <div><?php echo $this->_('Please use this form to upgrade your PHP Pro Bid v7 database to the latest version.'); ?></div>
    </blockquote>
<?php } ?>

<?php echo $this->form; ?>
<?php } ?>