<?php
/**
 * @version 7.4
 */
if ($sale instanceof \Ppb\Db\Table\Row\Sale) { ?>
    <?php echo $this->partial('partials/sale.phtml', array(
            'sale'                => $sale,
            'postageDesc'         => true,
            'caption'             => true,
            'directPaymentButton' => true,
            'type'                => $this->loggedInUser['id'] == $sale['seller_id'] ? 'sold' : 'bought')); ?>
<?php } ?>


<h4 class="headline">
    <span><?php echo $this->_('Message Board'); ?></span>
</h4>

<?php echo ($message['topic_id'] != null) ? $this->partial('partials/messages.phtml', array(
        'message' => $message)) : null; ?>
<?php echo $this->action('create', 'messaging', 'members', array(
    'receiver_id' => ($this->loggedInUser['id'] == $message['sender_id']) ?
            $message['receiver_id'] : $message['sender_id'],
    'sale_id'     => $message['sale_id'],
    'topic_id'    => $message['topic_id'])); ?>
