<?php
/**
 * @version 7.2
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta content="width=device-width; initial-scale=1.0; maximum-scale=1.0;" name="viewport"/>
    <title>Email</title>


    <style type="text/css">
        <!--
        body {
            background-color: #f2f2f2;
        }

        a {
            color: #f07057;
            text-decoration: none;
        }

        a:hover {
            color: #f07057;
            text-decoration: underline;
        }

        img {
            border: none;
            display: block;
        }

        .table {
            width: 100%;
        }

        .table td {
            font-family: sans-serif;
            font-size: 15px;
        }

        -->

        @media only screen and (max-width: 640px) {
            body {
                width: 100% !important;
            }

            table table {
                width: 500px !important;
            }
        }

        @media only screen and (max-width: 320px) {
            body {
                width: 100% !important;
            }

            table table {
                width: 300px !important;
            }
        }

    </style>

</head>
<body leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">

<table width="100% !important" height="100% !important" bgcolor="#f2f2f2" align="center" cellspacing="0" cellpadding="0"
       border="0"
       style="border-collapse:collapse!important;background-color:#f2f2f2;font-family:sans-serif;height:100%!important;margin:0;padding:0;width:100%!important">
    <tbody>
    <tr>
        <td width="100% !important" valign="top" height="100% !important" align="center"
            style="height:100%!important;margin:0;padding:0;width:100%!important">
            <table width="630" cellspacing="0" cellpadding="0" border="0"
                   style="border-collapse:collapse!important;width:630px;">
                <tbody>
                <tr>
                    <td valign="top" bgcolor="#f2f2f2" align="center"
                        style="padding:10px 20px;background-color:#f2f2f2">
                        <table width="100%" bgcolor="#ffffff" cellspacing="0" cellpadding="0" border="0"
                               style="border-collapse:separate!important;border-radius:4px;background-color:#ffffff;padding:30px;border:1px solid #cccccc;border-bottom:1px solid #acacac">
                            <tbody>
                            <tr>
                                <td valign="top" align="center">
                                    <table width="100%" cellspacing="0" cellpadding="0" border="0"
                                           style="border-collapse:collapse!important;width:100%;">
                                        <tbody>
                                        <tr>
                                            <td width="100%" valign="top" align="left"
                                                style="color:#444444;font-family:sans-serif;font-size:15px;line-height:150%;text-align:left">
                                                <table width="100%" cellspacing="0" cellpadding="0" border="0"
                                                       style="border-collapse:collapse!important">
                                                    <tbody>
                                                    <tr>
                                                        <td width="100.0%" valign="top" align="left"
                                                            style="text-align:left;font-family:sans-serif;font-size:15px;line-height:1.5em;color:#444444">
                                                            <a href="<?php echo $this->sitePath; ?>"><img
                                                                    src="<?php echo $this->sitePath; ?>/<?php echo $this->siteLogo; ?>"
                                                                    alt=""/></a>
                                                        </td>
                                                    </tr>
                                                    </tbody>
                                                </table>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td width="100%" valign="top" align="left"
                                                style="font-weight:bold;color:#333;font-family:sans-serif;font-size:22px;line-height:160%;padding-top:20px;text-align:left;border-bottom: 1px solid #acacac; ">
                                                <?php echo $this->_($this->headerMessage); ?>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td width="100%" valign="top" align="left"
                                                style="color:#444444;font-family:sans-serif;font-size:15px;line-height:150%;text-align:left;padding-top: 10px;">
                                                <!-- Add content here -->
                                                <?php echo $this->getContent(); ?>
                                            </td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td valign="top" align="center">
                        <table width="100%" bgcolor="#f2f2f2" align="center" cellspacing="0" cellpadding="0" border="0"
                               style="border-collapse:collapse!important;background-color:#f2f2f2;color:#999999;font-family:sans-serif;font-size:12px;line-height:120%;padding-top:20px;padding-right:20px;padding-bottom:20px;padding-left:20px;text-align:center">
                            <tbody>
                            <tr>
                                <td width="100%" valign="top" align="left"
                                    style="color:#444444;font-family:sans-serif;font-size:15px;line-height:150%;text-align:left">
                                    <table width="100%" cellspacing="0" cellpadding="0" border="0"
                                           style="border-collapse:collapse!important">
                                        <tbody>
                                        <tr>
                                            <td width="100.0%" valign="top" align="left"
                                                style="text-align:left;font-family:sans-serif;font-size:15px;line-height:1.5em;color:#444444">
                                                    <p align="center"
                                                       style="margin-bottom:1em;font-family:sans-serif;text-align:center;font-size:12px;line-height:1.34em;color:#999999;display:block">
                                                        <!-- Add footer code here -->
                                                        &copy;<?php echo date('Y'); ?>
                                                        <a href="<?php echo $this->sitePath; ?>"
                                                           style="color: #999;"><?php echo $this->siteName; ?></a>.
                                                        All rights reserved.

                                                    </p>
                                            </td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                </tbody>
            </table>
        </td>
    </tr>
    </tbody>
</table>

</body>
</html>