<!DOCTYPE html>
<html lang="en">
<head>
    <?php $assetsDir = $this->baseUrl . '/' . $this->themesFolder . "/standard/assets/"; ?>
    <title>Home</title>
    <meta charset="utf-8"/>
    <meta name="format-detection" content="telephone=no"/>
    <link rel="icon" href="<?= $assetsDir ?>images/favicon.png" type="image/png"/>
    <link rel="stylesheet" href="<?= $assetsDir ?>css/grid.css"/>
    <link rel="stylesheet" href="<?= $assetsDir ?>css/style.css"/>
    <link rel="stylesheet" href="<?= $assetsDir ?>css/owl-carousel.css"/>
    <link rel="stylesheet" href="<?= $assetsDir ?>css/google-map.css"/>
    <link rel="stylesheet" href="<?= $this->baseUrl . '/' ?>js/slick/slick.css"/>
    <link rel="stylesheet" href="<?= $this->baseUrl . '/' ?>js/slick/slick-theme.css"/>
    <script type="text/javascript">
        var baseAssetDir = "<?= $assetsDir ?>";
    </script>
    <script src="<?= $assetsDir ?>js/jquery.js"></script>
    <script src="<?= $this->baseUrl . '/' ?>js/slick/slick.min.js"></script><!--[if lt IE 9]>
    <script src="<?= $assetsDir ?>js/jquery.js"></script>
    <html class="lt-ie9">
    <div style="clear: both; text-align:center; position: relative;"><a href="http://windows.microsoft.com/en-US/internet-explorer/.."><img src="<?= $assetsDir ?>images/ie8-panel/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today."/></a></div>
    </html>
    <script src="<?= $assetsDir ?>js/html5shiv.js"></script><![endif]-->
    <script src="<?= $assetsDir ?>js/device.min.js"></script>
</head>
<body>
<div class="page">
    <header>
        <style type="text/css">
            .nav-container {
                position: absolute;
                top: -1.5rem;
                left: 0;
                right:0;
                text-align: left;
            }
            .nav-container .btn {
                color: #777;
                border-color: #777;
                display: inline-block;
                margin: 0;
                margin: 0 5px;
            }
            .nav-container .btn-menu {
                /*float: left;*/
            }
            .nav-container .btn-facebook, .nav-container .btn-register {
                float: right;
            }
            .nav {
                display: inline-block;
            }
            .nav > li {
                list-style: none;
                display: inline-block;
                line-height: 2.8em;
            }
            .nav > li > a {
                padding: 0.5em 0.5em 0;
                color: #616161;
                line-height: 2.22222em;
                vertical-align: middle;
            }
            #featured-video {
                width: 100%;
                position: absolute;
                top: 0;
                left: 0;
                right: 0;
                bottom: 0;
                padding: 0;
                margin: 0;
                overflow: hidden;
            }
            .jq-slider .img-advert {
                display: block;
                width: 95%;
                height: auto;
                margin: 0 auto;
            }

            .jq-slider {
                margin-bottom: 0px;
            }
            .slick-dots li button:before,
            .slick-dots li.slick-active button:before {
                color: #fff;
            }
            .slick-dots li button:before {
                font-size: 11px;
            }
        </style>
        <video id="featured-video" autoplay  poster="<?= $assetsDir ?>images/header-bg.jpg" loop>
            <source src="<?= $assetsDir ?>images/background.mp4" />
        </video>
        <div class="container" style="position: relative">
            <h1 class="brand"><a href="./"><img src="<?= $assetsDir ?>images/logo.png" alt=""/></a></h1>
            <div class="nav-container">
                <a class="btn btn-menu" href="#main-nav"><i class="fa fa-bars"></i>  Menu</a>
                <ul id="main-nav" class="nav" style="display: none;">
                    <li><a href="<?php echo $this->url(array('module' => 'members', 'controller' => 'stores', 'action' => 'index')); ?>">Auctions</a></li>
                    <li><a href="<?php echo $this->url("news"); ?>">News</a></li>
                    <li><a href="<?php echo $this->url("contact-us"); ?>">Contact us</a></li>
                    <?php
                    if (count($this->loggedInUser) == 0) { ?>
                        <li><a href="<?php echo $this->url(array('module' => 'members', 'controller' => 'user', 'action' => 'login')); ?>">Sign in</a></li>
                    <?php }
                    ?>
                </ul>
                <?php if (count($this->loggedInUser) > 0): ?>
                    <a class="btn btn-register" href="<?php echo $this->url(null, 'members-index'); ?>">Welcome, <?= $this->loggedInUser['username'] ?></a>
                <?php else: ?>
                    <a class="btn btn-register" href="<?php echo $this->url(array('module' => 'members', 'controller' => 'user', 'action' => 'register')); ?>">Sign up</a>
                    <a class="btn btn-facebook" href="<?php echo $this->url(array('module' => 'members', 'controller' => 'user', 'action' => 'facebook-login')); ?>"><i class="fa fa-facebook"></i> Sign in with Facebook</a>
                <?php endif; ?>
            </div>
        </div>
    </header>
    <script type="text/javascript">
        $(document).ready(function(){
            $(".btn-menu").on('click', function(e) {
                e.preventDefault();
                var navId = $(this).attr('href');
                $(navId).toggle();
            });
            $('.jq-slider').slick({
                dots: true,
                arrows: false,
                autoplay: true
            });
        });
    </script>
    <!--
    ========================================================
                                CONTENT
    ========================================================
    -->
    <main>
        <?php echo $this->getContent(); ?>

        <section class="well-1 well-inset-2"><span class="half-circle"><span>Visit our <br>shop</span></span>
            <div class="container center">
                <?php
                $adverts = $this->advert()->findBySection('slider', true);

                $nbAdverts = count($adverts);
                $activeClass = 'active';

                if ($nbAdverts > 0) {
                    ?>
                    <div class="jq-slider">
                        <?php foreach ($adverts as $advert) { ?>
                            <div>
                                <?php echo $this->advert($advert)->display(); ?>
                            </div>
                        <?php } ?>
                    </div>

                <?php } ?>

<!--                <div class="row inverse">-->
<!--                    <div class="col-md-1"></div>-->
<!--                    <div class="col-md-4">-->
<!--                        <img src="--><?//= $assetsDir ?><!--images/page-1_img04.jpg" alt="" class="circle">-->
<!--                        <h2 style="margin: 20px 0;">Shop 1 Ads</h2>-->
<!--                    </div>-->
<!--                    <div class="col-md-2"></div>-->
<!--                    <div class="col-md-4">-->
<!--                        <img src="--><?//= $assetsDir ?><!--images/page-1_img05.jpg" alt="" class="circle">-->
<!--                        <h2 style="margin: 20px 0;">Shop 2 Ads</h2>-->
<!--                    </div>-->
<!--                    <div class="col-md-1"></div>-->
<!--                </div>-->

                <!--
                <div class="row inverse">
                    <div class="col-md-4"></div>
                    <div class="col-md-4"><img src="<?/*= $assetsDir */?>images/page-1_img04.jpg" alt="" class="circle"></div>
                    <div class="col-md-4 md-right well-inset-1">
                        <h2>100% natural ingredients</h2>
                        <p class="text-muted">They quickly found a building with its own unique character that would be perfect for their brewery. They soon added Joel, their head brewer, to the team, who shared their passion for craft beer and had connections to both Mark and Paul (Mark and Joel grew up in Virginia, MN.</p><a href="#" class="btn hr-left">read more</a>
                    </div>
                </div>
                <div class="vertical-hr"></div>
                <div class="row">
                    <div class="col-md-4"></div>
                    <div class="col-md-4"><img src="<?/*= $assetsDir */?>images/page-1_img05.jpg" alt="" class="circle"></div>
                    <div class="col-md-4 md-left well-inset-1">
                        <h2>Limited edition beer</h2>
                        <p class="text-muted">Located in the historic Lyndale Theater in the LynLake neighborhood of Minneapolis, the brewery features a lineup of high-quality flagship craft beers along with seasonal rotations, specialties and the occasional one-off. Each is constructed to bring out the bold flavors and aromas of the high-quality ingredients.</p><a href="#" class="btn hr-right">read more</a>
                    </div>
                </div>
                <div class="vertical-hr"></div>
                <div class="row inverse">
                    <div class="col-md-4"></div>
                    <div class="col-md-4"><img src="<?/*= $assetsDir */?>images/page-1_img06.jpg" alt="" class="circle"></div>
                    <div class="col-md-4 md-right well-inset-1">
                        <h2>Progressive technologies</h2>
                        <p class="text-muted">Our product of our first double-mash brew filling up the mash tun once, running off all that sugary goodness, then filling up the mash once again in order to yield a highly concentrated wort. The result: a 9.5% kick in the ass. Amber candi syrup was used to further boost ABV and keep the body light.</p><a href="#" class="btn hr-left">read more</a>
                    </div>
                </div>
                -->
            </div>
        </section>
        <section data-url="<?= $assetsDir ?>images/parallax2.jpg" data-mobile="true" class="well-3 center parallax">
            <div class="container">
                <h2 class="uppercase">Craft brew news</h2>
                <div id="owl-carousel-3" class="owl-carousel">
                </div>
            </div>
        </section>
    </main>
    <footer>
        <section class="well-4">
            <div class="container">
                <div class="brand"><img src="<?= $assetsDir ?>images/logo.png" alt=""></div>
                <div class="copyright">© <span id="copyright-year"></span> <br> All Rights Reserved<!-- {%FOOTER_LINK} -->
                </div>
                <ul class="inline-list hr-both">
                    <li><a href="https://www.facebook.com/CraftbrewsAustralia" class="icon fa-facebook"></a></li>
                    <li><a href="https://twitter.com/team_Craftbrews" class="icon fa-twitter"></a></li>
                </ul>
            </div>
        </section>
        <section class="map">
            <div id="google-map" class="map_model"></div>
            <ul class="map_locations">
                <li data-y="-34.9257077" data-x="138.583259" data-zoom="13">
                    <p>640 Anzac HWY, Glenelg East, South Australia, 5045 <span>team@craftbrews.com.au</span></p>
                </li>
            </ul>
        </section>
    </footer>
</div>
<script src="<?= $assetsDir ?>js/script.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
        var news_template = '<blockquote class="item"><p><q><a href="{{link}}">{{title}}</a></q></p>{{excerpt}}<div class="hr-both"><a href="{{link}}">{{image}}</a></div></blockquote>';
        $.get('https://www.craftbrews.com.au/ppbv7/news/wp-json/wp/v2/posts?_embed', function(data) {
            // console.log(data);
            var html = "";
            data.forEach(function(e, i, a) {
                var temp = news_template.replace('{{title}}', e.title.rendered).replace('{{excerpt}}', e.excerpt.rendered).replace('{{link}}', e.link).replace('{{link}}', e.link);
                if (e.better_featured_image != undefined) {
                    temp = temp.replace('{{image}}', '<img src="' + e.better_featured_image.media_details.sizes.thumbnail.source_url + '" />');
                } else {
                    temp = temp.replace('{{image}}', '');
                }
                html += temp;
            });
            var o = $('#owl-carousel-3');
            o.html(html);
            if (o.length > 0) {
                o.owlCarousel({
                    margin: 30,
                    smartSpeed: 450,
                    loop: true,
                    dots: true,
                    dotsEach: 1,
                    nav: false,
                    navClass: ['owl-prev fa fa-angle-left', 'owl-next fa fa-angle-right'],
                    responsive: {
                        0: { items: 1 },
                        768: { items: 1},
                        980: { items: 1}
                    }
                });
            }
        });
//        $.get('<?//= $this->baseUrl ?>///social/twitter/data.json', function(data) {
//            var html = "";
//            data.forEach(function(e, i, a) {
//                var temp = news_template.replace('{{msg}}', e.msg).replace('{{display_name}}', e.display_name);
//                if (e.image != undefined) {
//                    temp = temp.replace('{{avatar}}', '<img src="' + e.image + ":thumb" + '" />');
//                } else {
//                    temp = temp.replace('{{avatar}}', '');
//                }
//                html += temp;
//            });
//            var o = $('#owl-carousel-3');
//            o.html(html);
//            if (o.length > 0) {
//                o.owlCarousel({
//                    margin: 30,
//                    smartSpeed: 450,
//                    loop: true,
//                    dots: true,
//                    dotsEach: 1,
//                    nav: false,
//                    navClass: ['owl-prev fa fa-angle-left', 'owl-next fa fa-angle-right'],
//                    responsive: {
//                        0: { items: 1 },
//                        768: { items: 1},
//                        980: { items: 1}
//                    }
//                });
//            }
//        });
    });
</script>
</body>
</html>