<?php
/**
 * @version 7.7
 */
?>
<!-- start - container -->
<div id="browse">
    <div class="row row-offcanvas row-offcanvas-left">
        <!-- start - side bar -->
        <aside class="col-sm-3 col-xs-12 sidebar-offcanvas">
            <div class="filter-results"><?php echo $this->_('Filter Results'); ?></div>
            <?php echo $this->action('stores', 'search', 'listings'); ?>
        </aside>
        <!-- end - side bar -->

        <!-- start - content -->
        <section class="col-sm-9 col-xs-12">
            <p class="visible-xs">
                <button class="btn btn-default" data-toggle="offcanvas" type="button">
                    <i class="fa fa-2x fa-list"></i>
                </button>
            </p>
            <!-- start - title -->
            <h1 class="section-title">
                <?php echo $this->_('Browse Stores'); ?>
            </h1>
            <!-- end - title -->

            <?php $featuredStoresContent = $this->action('featured', 'stores', 'members'); ?>
            <?php if (!empty($featuredStoresContent)) { ?>
                <div class="featured">
                    <h2><?php echo $this->_('Featured Stores'); ?></h2>
                    <?php echo $featuredStoresContent; ?>
                </div>
            <?php } ?>


            <?php if ($this->paginator->getPages()->totalItemCount) { ?>
                <!-- start - ordering/display options -->
                <div>
                    <div class="view-switch col-sm-2">
                        <a href="#" id="list"
                           title="<?php echo $this->_('List View'); ?>"><?php echo $this->_('List view'); ?></a>
                        <a href="#" id="grid"
                           title="<?php echo $this->_('Grid View'); ?>"><?php echo $this->_('Grid view'); ?></a>
                    </div>
                    <div class="col-sm-10">
                        <strong><?php echo $this->paginator->getPages()->totalItemCount; ?></strong> <?php echo $this->_('stores found.'); ?>
                        <?php if ($this->paginator->getPages()->totalItemCount) { ?>
                            <?php echo $this->_('Showing results'); ?>
                            <strong><?php echo $this->paginator->getPages()->firstItemNumber; ?></strong>
                            <?php echo $this->_('to'); ?>
                            <strong><?php echo $this->paginator->getPages()->lastItemNumber; ?></strong>.
                        <?php } ?>
                    </div>
                </div>
                <!-- end - ordering/display options -->

                <div class="clearfix"></div>

                <!-- start - listings display -->
                <div class="listings">
                    <?php
                    /* @var \Ppb\Db\Table\Row\User $store */
                    foreach ($this->paginator as $store) {
                        echo $this->partial('partials/store-box.phtml', array(
                            'store' => $store));
                    } ?>
                </div>
                <!-- end - listings display -->

                <div class="clearfix"></div>
            <?php } ?>

            <!-- start - paginate -->
            <div>
                <?php if (!$this->paginator->getPages()->totalItemCount) { ?>
                    <div class="no-results">
                        <?php echo $this->_('There are no stores matching your query.'); ?>
                    </div>
                <?php } ?>

                <div class="pull-right">
                    <?php echo $this->pagination($this->paginator, 'sliding', 'partials/pagination.phtml'); ?>
                </div>
            </div>
            <!-- end - paginate -->
        </section>
        <!-- end - content -->
    </div>

</div>
<!-- end - container -->
