<nav class="navbar navbar-filter">
    <!-- TODO: (optional) add option to create a language file directly from this page -->

    <form class="navbar-form navbar-right"
          action=""
          method="post">
        <div class="form-group">
            <label class="control-label">
                <?php echo $this->_('Select Email File'); ?>
            </label>
            <?php echo $this->formElement('select', 'email', $this->email)
                ->setMultiOptions(\Ppb\Utility::getSystemEmails())
                ->setAttributes(array(
                    'class' => 'form-control input-large'))
                ->render();
            ?>
        </div>
        <?php echo $this->formElement('submit', 'submit', $this->_('Proceed'))
            ->setAttributes(array('class' => 'btn btn-default'))
            ->render();
        ?>
    </form>
</nav>
<?php if ($this->email) { ?>
    <form action="" method="post">
        <input type="hidden" name="email" value="<?php echo $this->email; ?>">

        <div class="form-group">
            <?php echo $this->formElement('textarea', 'text')
                ->setAttributes(array(
                    'rows'  => '24',
                    'class' => 'form-control textarea-code',
                ))
                ->setValue($this->text)
                ->render(); ?>
            <span class="help-block">
                <?php echo $this->_('Recommended: you should edit this file using a dedicated editor, preferably one that recognizes php syntax. <br>'
                    . 'Important: adding invalid code to this file might render your site unusable.'); ?>
            </span>
        </div>

        <div class="form-group">
            <?php echo $this->formElement('submit', 'save', $this->_('Save'))
                ->setAttributes(array('class' => 'btn btn-primary'))
                ->render();
            ?>
        </div>
    </form>
<?php } ?>