<?php
$pages = array(10, 20, 40, 80);
?>
<div class="items-per-page">
    <ul class="pagination">
        <li><span><?php echo $this->_('Items per Page:'); ?></span></li>
        <?php foreach($pages as $page) { ?>
        <li <?php echo ($page == $itemsPerPage) ? 'class="active"' : ''; ?>>
            <a href="<?php echo $this->url(array('limit' => $page), null, true); ?>"><?php echo $page; ?></a>
        </li>
        <?php } ?>
    </ul>
</div>
