<?php /** @var \Ppb\Db\Table\Row\Listing $listing */ ?>
<?php if (count($listing) > 0) { ?>
    <blockquote class="bq bq-info">
        <p class="text-center">
            <a href="<?php echo $this->url($listing->link()); ?>" class="btn btn-success"><?php echo $this->_('View Listing'); ?></a>
            <?php echo $this->partial('partials/details-manage-buttons.phtml',
                array(
                    'listing' => $listing,
                    'live'    => true,
                    'user'    => $this->loggedInUser)); ?>
        </p>
    </blockquote>
<?php } ?>
