<?php $assetsDir = $this->baseUrl . '/' . $this->themesFolder . "/standard/assets/"; ?>
<section class="well-1 center"><span class="half-circle"><span>Virtual <br>tour</span></span>
    <div class="container">
        <h2 class="uppercase"><?= $news->title ?></h2>
        <?= $news->content ?>
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <?php echo $this->action('index', 'listing', 'home',
                    array(
                        'type'     => "featured",
                        'carousel' => "homepage",
                        'class'    => "test",
                        'limit'    => 6));
                ?>
            </div>
        </div>
    </div>
</section>

<section data-url="<?= $assetsDir ?>images/parallax1.jpg" data-mobile="true" class="well-2 center parallax">
    <div class="container">
        <div class="row">
            <?php echo $this->action('statistic', 'home', 'home'); ?>
        </div>
    </div>
</section>