<div class="alert alert-block alert-danger">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <a href="<?php echo $this->url(array('module' => 'members', 'controller' => 'user', 'action' => 'verification')); ?>"
       class="btn btn-danger btn-lg pull-right">
        <?php echo $this->_('Get Verified'); ?></a>
    <h4><?php echo $this->_('User Verification'); ?></h4>
    <?php echo $this->_("Please verify your account in order to take full advantage of our site's features."); ?>
</div>
