<?php
/**
 * @version 7.7
 */
/** @var \Ppb\Db\Table\Row\User $store */
$link = $this->url($store->storeLink());
$logo = $store->storeLogo();

$class = (!empty($class)) ? $class : 'list';
?>

<div class="<?php echo $class; ?>">
    <div class="image">
        <a href="<?php echo $link; ?>">
            <?php echo $this->thumbnail($logo, 200, true, array('alt' => $store->storeName())); ?>
        </a>
    </div>
    <div class="description">
        <div class="title">
            <h3><a href="<?php echo $link; ?>"><?php echo $store->storeName(); ?></a></h3>
            <p><?php echo $this->userDetails()->setUser($store)->storeDescription(false); ?></p>
        </div>

        <div class="owner">
            <div><?php echo $this->userDetails()->display(); ?></div>
            <div><?php echo $this->userDetails()->location(); ?></div>
        </div>
    </div>

</div>