<p>
    <?php echo sprintf(
        $this->_('The following listings that you have listed on %s have been closed:'),
        $this->siteName); ?>
</p>

<ul>
    <?php
    /** @var \Ppb\Db\Table\Row\Listing $listing */
    foreach ($this->data['listings'] as $listing) {
        ?>
        <li>
            <a href="<?php echo $this->sitePath . $this->url($listing->link(), null, false, null, false); ?>">
                [<?php echo $this->_('ID'); ?>: #<?php echo $listing['id']; ?> ] <?php echo $listing['name']; ?>
            </a>
        </li>
    <?php } ?>
</ul>
<p>
    <?php echo $this->_('Best regards'); ?> <br>
    <?php echo $this->siteName; ?>
</p>
