<?php
/**
 * @version 7.7
 */
if ($listing->countDependentRowset('\Ppb\Db\Table\Bids') > 0) {
    $bids = $listing->getBids();
    ?>
    <table class="table table-striped">
        <thead>
        <tr>
            <th><?php echo $this->_('Bidder'); ?></th>
            <th><?php echo $this->_('Amount'); ?></th>
            <th><?php echo $this->_('Date'); ?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($bids as $bid) { ?>
            <tr <?php echo (!$bid['outbid']) ? 'class="success"' : ''; ?>>
                <td><?php echo $this->userDetails()->setUser($bid->findParentRow('\Ppb\Db\Table\Users'))->display($listing['private_auction']); ?></td>
                <td><?php echo $this->amount($bid['amount'], $listing['currency']); ?></td>
                <td><?php echo $this->date($bid['created_at']); ?></td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
<?php }
else { ?>
    <div>
        <?php echo $this->_('The listing has no bids.'); ?>
    </div>
<?php } ?>
