<?php
/**
 * @version 7.2
 */
/**
 * MOD:- FACEBOOK LOGIN
 */
?>
<script type="text/javascript">
    $(document).ready(function () {
        var redirect = location.pathname;
        if (location.search) {
            redirect += location.search;
        }
        $('[name="redirect"]').val(redirect);
    });
</script>

<form class="form-modal" action="<?php echo $this->url(null, 'members-login'); ?>" method="post">
    <input type="hidden" name="redirect" value="">
    <input type="text" name="username" placeholder="<?php echo $this->_('Username / Email'); ?>" class="form-control"
           value="">
    <input type="password" name="password" placeholder="<?php echo $this->_('Password'); ?>" class="form-control"
           value="">

    <label class="checkbox">
        <input name="remember_me" type="checkbox" value="1"> <?php echo $this->_('Remember Me'); ?>
    </label>

    <p>
        <small>
            <a href="<?php echo $this->url(null, 'members-forgot-username'); ?>"><?php echo $this->_('Forgot your username'); ?></a>
            <?php echo $this->_('or'); ?>
            <a href="<?php echo $this->url(null, 'members-forgot-password'); ?>"><?php echo $this->_('Forgot your password'); ?></a>?
        </small>
    </p>

    <input class="btn btn-primary btn-lg btn-block" type="submit" name="login"
           value="<?php echo $this->_('Log In'); ?>">

    <hr>

    <?php if ($this->settings['enable_facebook_login']) { ?>
        <p class="text-center">
            <small><?php echo $this->_('or'); ?></small>
        </p>
        <a href="<?php echo $this->url(array('module' => 'members', 'controller' => 'user', 'action' => 'facebook-login')); ?>"
           class="btn btn-sm btn-default btn-block btn-register-facebook">
            <i class="fa fa-facebook-square"></i>
            <?php echo $this->_('Sign In Using Facebook'); ?>
        </a>
    <?php } ?>
</form>
