<?php /*
<div class="hidden-xs">
    <table class="table table-striped">
        <thead>
            <tr>
                <th colspan="3"><?php echo $this->translate('General'); ?></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    <a href="<?php echo $this->url(array('name' => 'signup'), 'fees'); ?>">
                        <?php echo $this->translate('User Signup'); ?>
                    </a>
                </td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th colspan="3"><?php echo $this->translate('Auctions / Products'); ?></th>
            </tr>
            <tr>
                <td>
                    <a href="<?php echo $this->url(array('name' => 'setup'), 'fees'); ?>">
                        <?php echo $this->translate('Listing Setup'); ?>
                    </a>
                </td>
                <td>
                    <a href="<?php echo $this->url(array('name' => 'sale'), 'fees'); ?>">
                        <?php echo $this->translate('Sale Transaction'); ?>
                    </a>
                </td>
                <td></td>
            </tr>
            <tr>
                <td>
                    <a href="<?php echo $this->url(array('name' => 'hpfeat'), 'fees'); ?>">
                        <?php echo $this->translate('Home Page Featuring'); ?>
                    </a>
                </td>
                <td>
                    <a href="<?php echo $this->url(array('name' => 'catfeat'), 'fees'); ?>">
                        <?php echo $this->translate('Category Pages Featuring'); ?>
                    </a>
                </td>
                <td>
                    <a href="<?php echo $this->url(array('name' => 'highlighted'), 'fees'); ?>">
                        <?php echo $this->translate('Highlighted Item'); ?>
                    </a>
                </td>
            </tr>
            <tr>
                <td>
                    <a href="<?php echo $this->url(array('name' => 'images'), 'fees'); ?>">
                        <?php echo $this->translate('Listing Images'); ?>
                    </a>
                </td>
                <td>
    <!--                <a href="<?php echo $this->url(array('name' => 'media'), 'fees'); ?>">
                        <?php echo $this->translate('Media Upload'); ?>
                    </a>                -->
                </td>
                <td>
    <!--                <a href="<?php echo $this->url(array('name' => 'digital_downloads'), 'fees'); ?>">
                        <?php echo $this->translate('Digital Downloads'); ?>
                    </a>                -->
                </td>
            </tr>
            <tr>
                <td>
                    <a href="<?php echo $this->url(array('name' => 'bold'), 'fees'); ?>">
                        <?php echo $this->translate('Bold Item'); ?>
                    </a>
                </td>
                <td>
                    <a href="<?php echo $this->url(array('name' => 'addl_category'), 'fees'); ?>">
                        <?php echo $this->translate('Additional Category Listing'); ?>
                    </a>
                </td>
                <td>
                    <a href="<?php echo $this->url(array('name' => 'reserve_price'), 'fees'); ?>">
                        <?php echo $this->translate('Reserve Price'); ?>
                    </a>
                </td>
            </tr>
            <tr>
                <td>
                    <a href="<?php echo $this->url(array('name' => 'buyout'), 'fees'); ?>">
                        <?php echo $this->translate('Buy Out'); ?>
                    </a>
                </td>
                <td>
                    <a href="<?php echo $this->url(array('name' => 'make_offer_fee'), 'fees'); ?>">
                        <?php echo $this->translate('Make Offer'); ?>
                    </a>
                </td>

                <td>
    <!--                <a href="<?php echo $this->url(array('name' => 'item_swap'), 'fees'); ?>">
                        <?php echo $this->translate('Item Swapping'); ?>
                    </a>-->
                </td>

            </tr>
    <!--        <tr>
                <td>
                    <a href="<?php echo $this->url(array('name' => 'relist_reduction'), 'fees'); ?>">
            <?php echo $this->translate('Relisting Fees Reduction'); ?>
                    </a>
                </td>
                <td>

                    <a href="<?php echo $this->url(array('name' => 'durations'), 'fees'); ?>">
            <?php echo $this->translate('Listing Durations'); ?>
                    </a>
                </td>
                <td>
                </td>
            </tr>        -->
        </tbody>

    </table>
</div>
*/ ?>
<?php echo $this->form; ?>