<?php
$class = null;

$currentBid = $listing->currentBid(true);

if ($currentBid > 0) {
    if ($listing['buyout_price'] == $currentBid) {
        $class = 'class="buyout-amount"';
    }
    else if ($currentBid < $listing['reserve_price']) {
        $class = 'class="under-reserve-amount"';
    }
    else if ($currentBid >= $listing['reserve_price']) {
        $class = 'class="over-reserve-amount"';
    } ?>
    <span <?php echo $class; ?>><?php echo $this->amount($currentBid, $listing['currency']); ?></span>
<?php } ?>
