<p>
    <?php echo sprintf(
        $this->_('A bid that you have placed on a listing from %s has been outbid.'),
        $this->siteName); ?>
</p>


<div>
    <?php echo $this->_('Listing details:'); ?>
</div>

<ul>
    <li>
        <?php echo $this->_('Name:'); ?>
        <b><?php echo $this->data['listing']['name']; ?></b>
    </li>
    <li>
        <?php echo $this->_('Listing page:'); ?>
        [ <a
            href="<?php echo $this->sitePath . $this->url($this->data['listing']->link(), null, false, null, false); ?>">
            <?php echo $this->_('click here'); ?>
        </a> ].
    </li>
</ul>
<div>
    <?php echo $this->_('Bid details:'); ?>
</div>
<ul>
    <li>
        <?php echo $this->_('Amount:'); ?>
        <b><?php echo $this->amount($this->data['bid']['amount'], $this->data['listing']['currency']); ?></b>
    </li>
</ul>
<p>
    <?php echo $this->_('Please'); ?>
    [ <a href="<?php echo $this->sitePath . $this->url($this->data['link'], null, false, null, false); ?>">
        <?php echo $this->_('click here'); ?>
    </a> ]
    <?php echo $this->_('to access your current bids page.'); ?>
    <?php echo $this->_('Please note that you will have to log in first.'); ?>
</p>

<p>
    <?php echo $this->_('Best regards'); ?> <br>
    <?php echo $this->siteName; ?>
</p>

