<?php
/**
 * @version 7.3
 */
?>

<p>
    <?php echo sprintf(
        $this->_('%s has sent you this item from %s for you to look at.'),
        $this->data['user']['username'],
        $this->siteName); ?>
</p>

<div><?php echo $this->_('Listing details:'); ?></div>
<ul>
    <li>
        <?php echo $this->_('Name:'); ?>
        <b><?php echo $this->data['listing']['name']; ?></b>
    </li>
    <li>
        <?php echo $this->_('Listing page:'); ?>
        [ <a
            href="<?php echo $this->sitePath . $this->url($this->data['listing']->link(), null, false, null, false); ?>">
            <?php echo $this->_('click here'); ?>
        </a> ].
    </li>

    <?php if (!empty($this->data['message'])) { ?>
        <li>
            <?php echo $this->_('Message:'); ?>
            <?php echo $this->data['message']; ?>
        </li>
    <?php } ?>
</ul>


<p>
    <?php echo $this->_('Best regards'); ?> <br>
    <?php echo $this->siteName; ?>
</p>