<?php
/**
 * @version 7.6
 */
?>
<p>
    <?php echo sprintf(
        $this->_('An offer that was placed on one of your listings from %s has been withdrawn.'),
        $this->siteName); ?>
</p>


<div>
    <?php echo $this->_('Listing details:'); ?>
</div>

<ul>
    <li>
        <?php echo $this->_('Name:'); ?>
        <b><?php echo $this->data['listing']['name']; ?></b>
    </li>
    <li>
        <?php echo $this->_('Listing page:'); ?>
        [ <a
            href="<?php echo $this->sitePath . $this->url($this->data['listing']->link(), null, false, null, false); ?>">
            <?php echo $this->_('click here'); ?>
        </a> ].
    </li>
</ul>
<div>
    <?php echo $this->_('Offer details:'); ?>
</div>
<ul>
    <?php if ($this->data['offer']['type'] == 'offer') { ?>
        <li>
            <?php echo $this->_('Amount:'); ?>
            <b><?php echo $this->amount($this->data['offer']['amount'], $this->data['listing']['currency']); ?>
                / <?php echo $this->_('item'); ?></b>
        </li>
    <?php } ?>
    <?php if (!empty($this->data['offer']['product_attributes'])) { ?>
        <li>
            <small><?php echo $this->productAttributes($this->data['offer']['product_attributes'])->display(); ?></small>
        </li>
    <?php } ?>
    <li>
        <?php echo $this->_('Quantity:'); ?>
        <b><?php echo $this->data['offer']['quantity']; ?></b>
    </li>
</ul>

<p>
    <?php echo $this->_('Please'); ?>
    [ <a href="<?php echo $this->sitePath . $this->url($this->data['link'], null, false, null, false); ?>">
        <?php echo $this->_('click here'); ?>
    </a> ]
    <?php echo $this->_('to access the offer details page.'); ?>
    <?php echo $this->_('Please note that you will have to log in first.'); ?>
</p>
<p>
    <?php echo $this->_('Best regards'); ?> <br>
    <?php echo $this->siteName; ?>
</p>

