<?php
/**
 * @version 7.4
 */
?>
<div class="login-form">
    <form method="<?php echo $this->form->getMethod(); ?>" action="<?php echo $this->form->getAction(); ?>">
        <?php echo $this->form->hiddenElements; ?>
        
        <legend><?php echo $this->translate('Login'); ?></legend>
        
        <?php foreach ((array) $this->messages as $message) { ?>
        <div class="alert <?php echo $message['class']; ?>">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <?php if (is_array($message['msg'])) { ?>
                <?php foreach ($message['msg'] as $msg) { ?>
                    <div><?php echo $this->translate($msg); ?></div>
                <?php } ?>
            <?php } else { ?>
                <?php echo $this->translate($message['msg']); ?>
        <?php } ?>
        </div>
        <?php } ?>
        
        <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-user"></i></span>
            <?php echo $this->form->username; ?>
        </div>
        <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-lock"></i></span>
            <?php echo $this->form->password; ?>
        </div>
        <?php /*
        <div>
            <img src="<?php echo $this->basePath; ?>/<?php echo $this->form->adminCaptcha; ?>">
        </div>
        <div class="input-prepend">                
            <span class="add-on"><i class="fa fa-envelope"></i></span>
            <?php echo $this->form->adminCaptcha; ?>
        </div>
         * 
         */ ?>
        <div class="input-group">
            <?php echo $this->form->submit; ?>
        </div>
    </form>
</div>