<p>
    <?php echo $this->_('A new listing,'); ?>
    <strong><?php echo $this->data['listing']['name']; ?></strong>,
    <?php echo $this->_('that requires admin approval has been posted.'); ?>
</p>

<div>
    <?php echo $this->_('Please'); ?>
    [ <a
        href="<?php echo $this->sitePath . $this->url(array('module' => 'admin', 'controller' => 'listings', 'action' => 'browse', 'listing_type' => 'all', 'filter' => 'awaiting_approval'), null, false, null, false); ?>">
        <?php echo $this->_('click here'); ?>
    </a> ]
    <?php echo $this->_('to access the page with all the listings that are awaiting approval.'); ?>
    <?php echo $this->_('Please note that you will have to log in first.'); ?>
</div>

