
<form action="<?php echo $this->form->getAction(); ?>" method="<?php echo $this->form->getMethod(); ?>" class="form-horizontal">
    <?php echo $this->form->hiddenElements; ?>

    <?php foreach ($this->form->getElements() as $element) { ?>
        <?php if (!$element->isHidden()) { ?>
            <?php echo $this->partial('partials/form-element.phtml', array('element' => $element)); ?>
        <?php } ?>
    <?php } ?>
</form>