<?php
/**
 * @version 7.7
 */
?>
<p style="text-align: center; border-top: 1px solid #e0e0e0; margin-top: 20px; padding-top: 10px;">
    <small>
        <?php echo $this->_('To manage your email notifications preferences, '); ?>
        <a href="<?php echo $this->sitePath . $this->url(array('module' => 'members', 'controller' => 'tools', 'action' => 'email-notifications'), null, false, null, false, false); ?>">
            <?php echo $this->_('click here'); ?>.
        </a>
    </small>
</p>