<form method="<?php echo $this->form->getMethod(); ?>" action="<?php echo $this->form->getAction(); ?>"
      class="form-horizontal">
    <?php echo $this->form->hiddenElements; ?>
    <?php
    /** @var \Cube\Form\Element $element */
    foreach ($this->form->getElements() as $element) {
        ?>
        <?php if (!$element->isHidden()) { ?>
            <?php echo $this->partial('partials/form-element.phtml', array('element' => $element)); ?>
        <?php } ?>
    <?php } ?>
</form>
