<?php
/**
 * @version 7.6
 */

if ($listingFees !== false) { ?>
    <div class="well">
        <h4 class="headline">
            <i class="fa fa-angle-right"></i>
            <span><?php echo $this->_('Listing Setup Fees'); ?></span>
        </h4>

        <div>
            <dl class="dl-horizontal">
                <?php if (count($listingFees) > 0) { ?>
                    <?php foreach ($listingFees as $row) { ?>
                        <dt><?php echo $this->_($row['name']); ?></dt>
                        <dd><?php echo $this->amount($row['amount']); ?></dd>
                    <?php } ?>
                <?php } ?>
                <dt class="fees-total"><?php echo $this->_('Total'); ?></dt>
                <dd class="fees-total"><?php echo $this->amount($listingSetupService->getTotalAmount()); ?>
                </dd>
            </dl>
        </div>
    </div>
<?php } ?>

<?php echo $this->form; ?>