<p>
    The installation has been completed successfully.
</p>
<p>
    To import your data from a previous PHP Pro Bid v6.x installation, please <a href="<?php echo $this->url(array('action' => 'importer')); ?>">click here</a>.
</p>
<p>
    Otherwise, <a href="<?php echo $this->url(null, 'app-home'); ?>">click here</a> to access your website. Please note that you will have to activate your license first.
</p>