<?php
/**
 * @version 7.4
 */
?>
    <form action="<?php echo $this->form->getAction(); ?>" method="<?php echo $this->form->getMethod(); ?>"
          id="left-side-search">
        <?php echo $this->form->hiddenElements; ?>
        <ul class="search">
            <?php
            /** @var \Cube\Form\Element $element */
            foreach ($this->form->getElements() as $element) {
                if (!$element->isHidden()) { ?>
                    <li>
                        <a><?php echo $element->getLabel(); ?></a>
                        <ul>
                            <li><?php echo $element->render(); ?></li>
                        </ul>
                    </li>
                <?php }
            } ?>
        </ul>
    </form>

<?php
$this->script()->addBodyCode("
    <script type=\"text/javascript\">
        $(document).ready(function(){
            // left side search filter form submit on checkbox click or select change
            // do not name anything 'submit' or the below snippet will not trigger!
            $('#left-side-search input[type=\"checkbox\"]').on('click', function() {
                $(this).closest('form').submit();
            });
        });
    </script>");
?>