<!--
left navigation view partial
displaying only one level of submenus, all menus and submenus except for the
heading will have links.
accordion is also disabled
-->


<ul class="nav nav-list">

    <li class="nav-header">
        <?php if (isset($this->menu->icon)) { ?>
            <i class="<?php echo $this->menu->icon; ?>"></i>
        <?php } ?>
        <?php echo $this->menu->label; ?>
    </li>
    <?php foreach ($this->menu->pages as $key => $page) { ?>
        <?php if ((!$page->settings || (intval($this->settings[(string)$page->settings['name']]) == $page->settings['value'])) &&
                  $this->navigation()->accept($page) &&
                  $page->hidden != 'true'
        ) {
            ?>

            <li class="nav-subheader<?php echo ($page->isActive(true)) ? ' active' : ''; ?>">
                <a href="<?php echo $this->url($page->params); ?>">
                    <?php echo $page->label; ?>
                </a>
            </li>

            <?php if (!empty($page->pages)) { ?>
                <?php foreach ($page->pages as $subKey => $subPage) { ?>
                    <?php if ((!$subPage->settings || (intval($this->settings[(string)$subPage->settings['name']]) == $subPage->settings['value'])) &&
                              $this->navigation()->accept($subPage) &&
                              $subPage->hidden != 'true'
                    ) {
                        ?>
                        <li class="nav-tab<?php echo ($subPage->isActive(true)) ? ' active' : ''; ?>">
                            <a href="<?php echo $this->url($subPage->params); ?>">
                                <?php echo $subPage->label; ?>
                            </a>
                        </li>
                    <?php } ?>
                <?php } ?>
            <?php } ?>

        <?php } ?>
    <?php } ?>
</ul>
